# Generated by Django 5.2.5 on 2025-08-30 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the food item')),
                ('calories_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, help_text='Protein in grams', max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, help_text='Carbohydrates in grams', max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, help_text='Fat in grams', max_digits=6)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, help_text='Fiber in grams', max_digits=6)),
                ('serving_size_g', models.DecimalField(decimal_places=1, default=100, help_text='Common serving size in grams', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.DecimalField(decimal_places=1, help_text='Quantity consumed in grams', max_digits=6)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='counter.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food entries',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.DecimalField(decimal_places=0, default=2000, help_text='Daily calorie target', max_digits=6)),
                ('daily_protein', models.DecimalField(decimal_places=1, default=150, help_text='Daily protein target in grams', max_digits=6)),
                ('daily_carbs', models.DecimalField(decimal_places=1, default=250, help_text='Daily carbohydrates target in grams', max_digits=6)),
                ('daily_fat', models.DecimalField(decimal_places=1, default=70, help_text='Daily fat target in grams', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
